language: cpp
dist: xenial

script:
- echo $AMDAPPSDKROOT
- cmake --version
- clinfo
- mkdir build && cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ctest -V; fi

before_install:
- eval "${MATRIX_EVAL}"

install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export BLOCKS_FLAG=2; export THREADS_FLAG=1; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export BLOCKS_FLAG=8; export THREADS_FLAG=8; fi

matrix:
  include:

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_script:
        - brew update
        - brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_script:
        - brew update
        - brew install llvm@4 && brew link --overwrite llvm@4 --force
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_script:
        - brew update
        - brew install llvm@5 && brew link --overwrite llvm@5 --force
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++"
      before_script:
        - brew update
        - brew install llvm@6 && brew link --overwrite llvm@6 --force
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++"
      before_script:
        - brew update
        - brew install llvm@7 && brew link --overwrite llvm@7 --force
        - export PATH="/usr/local/opt/llvm/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/llvm/lib"
        - export CPPFLAGS="-I/usr/local/opt/llvm/include"
        - brew install clinfo

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - brew update
        - brew install gcc@4.9
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - brew update
        - brew install gcc@5
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        - brew update
        - brew install gcc@6
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - brew update
        - brew install gcc@7
        - brew install clinfo
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_script:
        - brew update
        - brew install gcc@8
        - brew install clinfo

    ######## LINUX CLANG ########
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      before_script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main"
        - sudo apt update
        - sudo apt-get install clang-3.9
        - sudo apt-get install libomp-dev
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      before_script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main"
        - sudo apt update
        - sudo apt-get install clang-4.0
        - sudo apt-get install libomp-dev
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      before_script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main"
        - sudo apt update
        - sudo apt-get install clang-5.0
        - sudo apt-get install libomp-dev
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      before_script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
        - sudo apt update
        - sudo apt-get install clang-6.0
        - sudo apt-get install libomp-dev
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
      before_script:
        - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
        - sudo apt-add-repository "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
        - sudo apt update
        - sudo apt-get install clang-7
        - sudo apt-get install libomp-dev
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh

    ######## LINUX GCC ########
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-4.9
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-5
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-6
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-7
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_script:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        - sudo apt-get update
        - sudo apt-get install g++-8
        - sudo apt-get install opencl-headers clinfo
        - source scripts/opencl_install.sh
        - source scripts/cmake_install.sh
