language: cpp
dist: xenial

script:
  - cmake --version
  - python --version
  - clinfo
#  - pushd .
#  - cd data/a/
#  - python a.py
#  - popd
#  - pushd .
#  - cd data/b/
#  - python b.py
#  - popd
#  - pushd .
#  - cd data/c/
#  - python c.py
#  - popd
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config Release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ctest -V; fi

before_script:
  - eval "${MATRIX_EVAL}"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then export BLOCKS_FLAG=2; export THREADS_FLAG=1; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export BLOCKS_FLAG=8; export THREADS_FLAG=8; fi

matrix:
  include:

    ######## OSX CLANG ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++"
      before_install:
        - brew install llvm@3.9 && brew link --overwrite llvm@3.9 --force
      install: &mac_extra
        - brew install clinfo
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++"
      before_install:
        - brew install llvm@4 && brew link --overwrite llvm@4 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++"
      before_install:
        - brew install llvm@5 && brew link --overwrite llvm@5 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++"
      before_install:
        - brew install llvm@6 && brew link --overwrite llvm@6 --force
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++"
      before_install:
        - brew install llvm@7 && brew link --overwrite llvm@7 --force
        - export PATH="/usr/local/opt/llvm/bin:$PATH"
        - export LDFLAGS="-L/usr/local/opt/llvm/lib"
        - export CPPFLAGS="-I/usr/local/opt/llvm/include"
      install: *mac_extra

    ######## OSX GCC ########
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
        - brew install gcc@4.9
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      before_install:
        - brew install gcc@5
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      before_install:
        - brew install gcc@6
      install: *mac_extra
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - brew install gcc@7
      install: *mac_extra
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      before_install:
        - brew install gcc@8
      install: *mac_extra

    ######## LINUX CLANG ########
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.9
            - libomp-dev
      install: &linux_extras
        - sudo apt-get install opencl-headers clinfo
        - source scripts/intel_opencl_install.sh
        - source scripts/cmake_install.sh
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-4.0
            - libomp-dev
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
            - libomp-dev
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - libomp-dev
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
      addons:
        apt:
          sources:
            - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - libomp-dev
      install: *linux_extras

    ######## LINUX GCC ########
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-4.9
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-5
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-6
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
      install: *linux_extras
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-8
      install: *linux_extras
